/*
 * BitBuggy Shipping
 *
 * Management of shipping and delivery information.
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using BitBuggy.Shipping.Maui.Shipping.Client;
using BitBuggy.Shipping.Maui.Shipping.Model;

namespace BitBuggy.Shipping.Maui.Shipping.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get User Deliveries
        /// </summary>
        /// <remarks>
        /// Get all the deliveries for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Delivery&gt;</returns>
        List<Delivery> GetUserDeliveries(Guid userId, int operationIndex = 0);

        /// <summary>
        /// Get User Deliveries
        /// </summary>
        /// <remarks>
        /// Get all the deliveries for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Delivery&gt;</returns>
        ApiResponse<List<Delivery>> GetUserDeliveriesWithHttpInfo(Guid userId, int operationIndex = 0);
        /// <summary>
        /// Get User Shipment
        /// </summary>
        /// <remarks>
        /// Get a specific shipment for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Shipment</returns>
        Shipment GetUserShipment(Guid userId, Guid shipmentId, int operationIndex = 0);

        /// <summary>
        /// Get User Shipment
        /// </summary>
        /// <remarks>
        /// Get a specific shipment for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Shipment</returns>
        ApiResponse<Shipment> GetUserShipmentWithHttpInfo(Guid userId, Guid shipmentId, int operationIndex = 0);
        /// <summary>
        /// Get User Shipment Status
        /// </summary>
        /// <remarks>
        /// Get the status of a shipment for the currently logged in user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ShipmentStatus</returns>
        ShipmentStatus GetUserShipmentStatus(Guid userId, Guid shipmentId, int operationIndex = 0);

        /// <summary>
        /// Get User Shipment Status
        /// </summary>
        /// <remarks>
        /// Get the status of a shipment for the currently logged in user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ShipmentStatus</returns>
        ApiResponse<ShipmentStatus> GetUserShipmentStatusWithHttpInfo(Guid userId, Guid shipmentId, int operationIndex = 0);
        /// <summary>
        /// Get User Shipments
        /// </summary>
        /// <remarks>
        /// Get all the shipments for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Shipment&gt;</returns>
        List<Shipment> GetUserShipments(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0);

        /// <summary>
        /// Get User Shipments
        /// </summary>
        /// <remarks>
        /// Get all the shipments for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Shipment&gt;</returns>
        ApiResponse<List<Shipment>> GetUserShipmentsWithHttpInfo(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get User Deliveries
        /// </summary>
        /// <remarks>
        /// Get all the deliveries for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Delivery&gt;</returns>
        System.Threading.Tasks.Task<List<Delivery>> GetUserDeliveriesAsync(Guid userId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get User Deliveries
        /// </summary>
        /// <remarks>
        /// Get all the deliveries for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Delivery&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Delivery>>> GetUserDeliveriesWithHttpInfoAsync(Guid userId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get User Shipment
        /// </summary>
        /// <remarks>
        /// Get a specific shipment for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Shipment</returns>
        System.Threading.Tasks.Task<Shipment> GetUserShipmentAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get User Shipment
        /// </summary>
        /// <remarks>
        /// Get a specific shipment for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Shipment)</returns>
        System.Threading.Tasks.Task<ApiResponse<Shipment>> GetUserShipmentWithHttpInfoAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get User Shipment Status
        /// </summary>
        /// <remarks>
        /// Get the status of a shipment for the currently logged in user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ShipmentStatus</returns>
        System.Threading.Tasks.Task<ShipmentStatus> GetUserShipmentStatusAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get User Shipment Status
        /// </summary>
        /// <remarks>
        /// Get the status of a shipment for the currently logged in user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ShipmentStatus)</returns>
        System.Threading.Tasks.Task<ApiResponse<ShipmentStatus>> GetUserShipmentStatusWithHttpInfoAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get User Shipments
        /// </summary>
        /// <remarks>
        /// Get all the shipments for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Shipment&gt;</returns>
        System.Threading.Tasks.Task<List<Shipment>> GetUserShipmentsAsync(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get User Shipments
        /// </summary>
        /// <remarks>
        /// Get all the shipments for a given user.
        /// </remarks>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Shipment&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Shipment>>> GetUserShipmentsWithHttpInfoAsync(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IUsersApi : IUsersApiSync, IUsersApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class UsersApi : IUsersApi
    {
        private BitBuggy.Shipping.Maui.Shipping.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsersApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class.
        /// </summary>
        /// <returns></returns>
        public UsersApi(string basePath)
        {
            this.Configuration = BitBuggy.Shipping.Maui.Shipping.Client.Configuration.MergeConfigurations(
                BitBuggy.Shipping.Maui.Shipping.Client.GlobalConfiguration.Instance,
                new BitBuggy.Shipping.Maui.Shipping.Client.Configuration { BasePath = basePath }
            );
            this.Client = new BitBuggy.Shipping.Maui.Shipping.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new BitBuggy.Shipping.Maui.Shipping.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = BitBuggy.Shipping.Maui.Shipping.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public UsersApi(BitBuggy.Shipping.Maui.Shipping.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = BitBuggy.Shipping.Maui.Shipping.Client.Configuration.MergeConfigurations(
                BitBuggy.Shipping.Maui.Shipping.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new BitBuggy.Shipping.Maui.Shipping.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new BitBuggy.Shipping.Maui.Shipping.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = BitBuggy.Shipping.Maui.Shipping.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="UsersApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public UsersApi(BitBuggy.Shipping.Maui.Shipping.Client.ISynchronousClient client, BitBuggy.Shipping.Maui.Shipping.Client.IAsynchronousClient asyncClient, BitBuggy.Shipping.Maui.Shipping.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = BitBuggy.Shipping.Maui.Shipping.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public BitBuggy.Shipping.Maui.Shipping.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public BitBuggy.Shipping.Maui.Shipping.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public BitBuggy.Shipping.Maui.Shipping.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public BitBuggy.Shipping.Maui.Shipping.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get User Deliveries Get all the deliveries for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Delivery&gt;</returns>
        public List<Delivery> GetUserDeliveries(Guid userId, int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Delivery>> localVarResponse = GetUserDeliveriesWithHttpInfo(userId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Deliveries Get all the deliveries for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Delivery&gt;</returns>
        public BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Delivery>> GetUserDeliveriesWithHttpInfo(Guid userId, int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter

            localVarRequestOptions.Operation = "UsersApi.GetUserDeliveries";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Delivery>>("/users/{user_id}/deliveries", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserDeliveries", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Deliveries Get all the deliveries for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Delivery&gt;</returns>
        public async System.Threading.Tasks.Task<List<Delivery>> GetUserDeliveriesAsync(Guid userId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Delivery>> localVarResponse = await GetUserDeliveriesWithHttpInfoAsync(userId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Deliveries Get all the deliveries for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Delivery&gt;)</returns>
        public async System.Threading.Tasks.Task<BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Delivery>>> GetUserDeliveriesWithHttpInfoAsync(Guid userId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter

            localVarRequestOptions.Operation = "UsersApi.GetUserDeliveries";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Delivery>>("/users/{user_id}/deliveries", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserDeliveries", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Shipment Get a specific shipment for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Shipment</returns>
        public Shipment GetUserShipment(Guid userId, Guid shipmentId, int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<Shipment> localVarResponse = GetUserShipmentWithHttpInfo(userId, shipmentId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Shipment Get a specific shipment for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Shipment</returns>
        public BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<Shipment> GetUserShipmentWithHttpInfo(Guid userId, Guid shipmentId, int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shipment_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(shipmentId)); // path parameter

            localVarRequestOptions.Operation = "UsersApi.GetUserShipment";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Shipment>("/users/{user_id}/shipments/{shipment_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserShipment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Shipment Get a specific shipment for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Shipment</returns>
        public async System.Threading.Tasks.Task<Shipment> GetUserShipmentAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<Shipment> localVarResponse = await GetUserShipmentWithHttpInfoAsync(userId, shipmentId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Shipment Get a specific shipment for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Shipment)</returns>
        public async System.Threading.Tasks.Task<BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<Shipment>> GetUserShipmentWithHttpInfoAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shipment_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(shipmentId)); // path parameter

            localVarRequestOptions.Operation = "UsersApi.GetUserShipment";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Shipment>("/users/{user_id}/shipments/{shipment_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserShipment", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Shipment Status Get the status of a shipment for the currently logged in user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ShipmentStatus</returns>
        public ShipmentStatus GetUserShipmentStatus(Guid userId, Guid shipmentId, int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<ShipmentStatus> localVarResponse = GetUserShipmentStatusWithHttpInfo(userId, shipmentId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Shipment Status Get the status of a shipment for the currently logged in user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of ShipmentStatus</returns>
        public BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<ShipmentStatus> GetUserShipmentStatusWithHttpInfo(Guid userId, Guid shipmentId, int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shipment_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(shipmentId)); // path parameter

            localVarRequestOptions.Operation = "UsersApi.GetUserShipmentStatus";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<ShipmentStatus>("/users/{user_id}/shipments/{shipment_id}/status", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserShipmentStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Shipment Status Get the status of a shipment for the currently logged in user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ShipmentStatus</returns>
        public async System.Threading.Tasks.Task<ShipmentStatus> GetUserShipmentStatusAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<ShipmentStatus> localVarResponse = await GetUserShipmentStatusWithHttpInfoAsync(userId, shipmentId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Shipment Status Get the status of a shipment for the currently logged in user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="shipmentId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (ShipmentStatus)</returns>
        public async System.Threading.Tasks.Task<BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<ShipmentStatus>> GetUserShipmentStatusWithHttpInfoAsync(Guid userId, Guid shipmentId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter
            localVarRequestOptions.PathParameters.Add("shipment_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(shipmentId)); // path parameter

            localVarRequestOptions.Operation = "UsersApi.GetUserShipmentStatus";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<ShipmentStatus>("/users/{user_id}/shipments/{shipment_id}/status", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserShipmentStatus", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Shipments Get all the shipments for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;Shipment&gt;</returns>
        public List<Shipment> GetUserShipments(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Shipment>> localVarResponse = GetUserShipmentsWithHttpInfo(userId, limit, offset, dateDesc, status, provider, fromAddress, shippingAddress, deliveryId, trackingId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Shipments Get all the shipments for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;Shipment&gt;</returns>
        public BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Shipment>> GetUserShipmentsWithHttpInfo(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0)
        {
            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (dateDesc != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "date_desc", dateDesc));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (provider != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "provider", provider));
            }
            if (fromAddress != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "from_address", fromAddress));
            }
            if (shippingAddress != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "shipping_address", shippingAddress));
            }
            if (deliveryId != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "delivery_id", deliveryId));
            }
            if (trackingId != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "tracking_id", trackingId));
            }

            localVarRequestOptions.Operation = "UsersApi.GetUserShipments";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<List<Shipment>>("/users/{user_id}/shipments", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserShipments", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get User Shipments Get all the shipments for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;Shipment&gt;</returns>
        public async System.Threading.Tasks.Task<List<Shipment>> GetUserShipmentsAsync(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Shipment>> localVarResponse = await GetUserShipmentsWithHttpInfoAsync(userId, limit, offset, dateDesc, status, provider, fromAddress, shippingAddress, deliveryId, trackingId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get User Shipments Get all the shipments for a given user.
        /// </summary>
        /// <exception cref="BitBuggy.Shipping.Maui.Shipping.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="userId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="offset"> (optional, default to 0)</param>
        /// <param name="dateDesc"> (optional, default to true)</param>
        /// <param name="status"> (optional)</param>
        /// <param name="provider"> (optional)</param>
        /// <param name="fromAddress"> (optional)</param>
        /// <param name="shippingAddress"> (optional)</param>
        /// <param name="deliveryId"> (optional)</param>
        /// <param name="trackingId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;Shipment&gt;)</returns>
        public async System.Threading.Tasks.Task<BitBuggy.Shipping.Maui.Shipping.Client.ApiResponse<List<Shipment>>> GetUserShipmentsWithHttpInfoAsync(Guid userId, int? limit = default(int?), int? offset = default(int?), bool? dateDesc = default(bool?), Status? status = default(Status?), Provider? provider = default(Provider?), string? fromAddress = default(string?), string? shippingAddress = default(string?), string? deliveryId = default(string?), string? trackingId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions localVarRequestOptions = new BitBuggy.Shipping.Maui.Shipping.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("user_id", BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToString(userId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (offset != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "offset", offset));
            }
            if (dateDesc != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "date_desc", dateDesc));
            }
            if (status != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "status", status));
            }
            if (provider != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "provider", provider));
            }
            if (fromAddress != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "from_address", fromAddress));
            }
            if (shippingAddress != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "shipping_address", shippingAddress));
            }
            if (deliveryId != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "delivery_id", deliveryId));
            }
            if (trackingId != null)
            {
                localVarRequestOptions.QueryParameters.Add(BitBuggy.Shipping.Maui.Shipping.Client.ClientUtils.ParameterToMultiMap("", "tracking_id", trackingId));
            }

            localVarRequestOptions.Operation = "UsersApi.GetUserShipments";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<List<Shipment>>("/users/{user_id}/shipments", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetUserShipments", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
