/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BitBuggy.Shipping.Maui.Shipping.Client.OpenAPIDateConverter;

namespace BitBuggy.Shipping.Maui.Shipping.Model
{
    /// <summary>
    /// Represents a full delivery, composed of the individual orders. This is a simple composite model to represent all the orders that this is made of.
    /// </summary>
    [DataContract(Name = "Delivery")]
    public partial class Delivery : IValidatableObject
    {

        /// <summary>
        /// Gets or Sets DeliverySla
        /// </summary>
        [DataMember(Name = "delivery_sla", IsRequired = true, EmitDefaultValue = true)]
        public SLA DeliverySla { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="Delivery" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Delivery() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Delivery" /> class.
        /// </summary>
        /// <param name="deliveryId">deliveryId (required).</param>
        /// <param name="orderId">orderId (required).</param>
        /// <param name="shipments">shipments (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="deliverySla">deliverySla (required).</param>
        public Delivery(Guid deliveryId = default(Guid), Guid orderId = default(Guid), List<Shipment> shipments = default(List<Shipment>), DateTime createdAt = default(DateTime), SLA deliverySla = default(SLA))
        {
            this.DeliveryId = deliveryId;
            this.OrderId = orderId;
            // to ensure "shipments" is required (not null)
            if (shipments == null)
            {
                throw new ArgumentNullException("shipments is a required property for Delivery and cannot be null");
            }
            this.Shipments = shipments;
            this.CreatedAt = createdAt;
            this.DeliverySla = deliverySla;
        }

        /// <summary>
        /// Gets or Sets DeliveryId
        /// </summary>
        [DataMember(Name = "delivery_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid DeliveryId { get; set; }

        /// <summary>
        /// Gets or Sets OrderId
        /// </summary>
        [DataMember(Name = "order_id", IsRequired = true, EmitDefaultValue = true)]
        public Guid OrderId { get; set; }

        /// <summary>
        /// Gets or Sets Shipments
        /// </summary>
        [DataMember(Name = "shipments", IsRequired = true, EmitDefaultValue = true)]
        public List<Shipment> Shipments { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Delivery {\n");
            sb.Append("  DeliveryId: ").Append(DeliveryId).Append("\n");
            sb.Append("  OrderId: ").Append(OrderId).Append("\n");
            sb.Append("  Shipments: ").Append(Shipments).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  DeliverySla: ").Append(DeliverySla).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
