/*
 * BitBuggy Shipping
 *
 * Management of shipping and delivery information.
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BitBuggy.Shipping.Maui.Shipping.Client.OpenAPIDateConverter;

namespace BitBuggy.Shipping.Maui.Shipping.Model
{
    /// <summary>
    /// Represents the different providers that can be used to ship a package.
    /// </summary>
    /// <value>Represents the different providers that can be used to ship a package.</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum Provider
    {
        /// <summary>
        /// Enum Ups for value: ups
        /// </summary>
        [EnumMember(Value = "ups")]
        Ups = 1,

        /// <summary>
        /// Enum Fedex for value: fedex
        /// </summary>
        [EnumMember(Value = "fedex")]
        Fedex = 2,

        /// <summary>
        /// Enum Usps for value: usps
        /// </summary>
        [EnumMember(Value = "usps")]
        Usps = 3,

        /// <summary>
        /// Enum Internal for value: internal
        /// </summary>
        [EnumMember(Value = "internal")]
        Internal = 4
    }

}
